networks:
  application:
    driver: bridge

services:
  backend:
    build:
      context: ./auth-app
      dockerfile: Dockerfile
    container_name: auth-docker-app
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ./auth-app:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=postgresdb
      - VITE_URL="http://host.docker.internal:5173" #alias especial do Docker que aponta para o IP do host
    networks:
      - application
    working_dir: /var/www/html
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        php artisan key:generate && \
        php artisan migrate --force && \
        npm install && \
        npm run dev & \
        php artisan serve --host=0.0.0.0 --port=8000
  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    networks:
      - application
    container_name: postgresdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
